import type { Metadata } from "next";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Highlighter from "@/components/Highlighter";
import Watermark from "@/components/Watermark";
import fonts from "@/lib/fonts";
import Tweaks from "@/components/Tweaks";
import { getCookie } from "@/lib/actions";
import { COOKIES_NAMES } from "@/data/app";

export const metadata: Metadata = {
  title: "Suraj Vijayan — Portfolio",
  description: "Generated by create next app",
};

const RootLayout: React.FC<React.PropsWithChildren> = async ({ children }) => {
  // server actions
  const locale = await getLocale();
  const messages = await getMessages();
  const font = (await getCookie<App.Font>(COOKIES_NAMES.font)) ?? "editorial";
  const theme = (await getCookie<App.Theme>(COOKIES_NAMES.theme)) ?? "sepia";

  return (
    <html
      lang={locale}
      data-texture="on"
      data-font={font}
      data-theme={theme}
      className={`${fonts.newsreader.variable} ${fonts.newsreaderItalic.variable} ${fonts.interTight.variable} ${fonts.jetbrainsMono.variable} ${fonts.cormorant.variable} ${fonts.spaceGrotesk.variable} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <Highlighter />
          <Watermark />
          {children}
          <Tweaks font={font} theme={theme} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
