import "./globals.css";

import type { Metadata } from "next";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

// custom
import Highlighter from "@/components/Highlighter";
import Watermark from "@/components/Watermark";
import fonts from "@/lib/fonts";
import Tweaks from "@/components/Tweaks";
import { getCookie } from "@/lib/actions";
import { COOKIES_NAMES } from "@/data/app";

export const metadata: Metadata = {
  title: "Suraj Vijayan — Portfolio",
  description: "Generated by create next app",
};

const RootLayout: React.FC<React.PropsWithChildren> = async ({ children }) => {
  // server actions
  const messages = await getMessages();

  // cookies
  const theme = (await getCookie<App.Theme>(COOKIES_NAMES.theme)) ?? "sepia";
  const font = (await getCookie<App.Font>(COOKIES_NAMES.font)) ?? "editorial";
  const locale = ((await getLocale()) ?? "en") as App.LanguageCode;
  const density =
    (await getCookie<App.Density>(COOKIES_NAMES.density)) ?? "airy";
  const texture = (await getCookie<App.Texture>(COOKIES_NAMES.texture)) ?? "on";

  return (
    <html
      lang={locale}
      data-texture={texture}
      data-font={font}
      data-theme={theme}
      className={`${fonts.newsreader.variable} ${fonts.newsreaderItalic.variable} ${fonts.interTight.variable} ${fonts.jetbrainsMono.variable} ${fonts.cormorant.variable} ${fonts.spaceGrotesk.variable} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <Highlighter />
          <Watermark />
          {children}
          <Tweaks {...{ font, theme, locale, density, texture }} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
