export const resume = {
  name: "Suraj Vijayan",
  tagline: "Founding engineer. Frontend systems at scale, shipped one brick at a time.",
  currently: "Building the Good Bards platform — 78 pages, 652 components, 25 enterprise clients.",
  contact: {
    github: "its-me-sv",
    email: "surajvijay67@gmail.com",
    linkedin: "suraj-vijay-32b679224",
    instagram: "suraj_vijay_115.py",
    site: "surajvijayan.me",
  },
  experience: [
    {
      id: "gb-founding",
      role: "Founding Engineer",
      company: "Good Bards",
      type: "Full-time",
      start: "Oct 2024",
      end: "Present",
      stack: ["Next.js","React","TypeScript","Redux Toolkit","shadcn/ui","Tailwind CSS","Node.js","REST APIs","OAuth"],
      bullets: [
        "Rebuilt the frontend platform across 1,000+ hours, shipping 78 pages, 652 components, and ~36K LOC now used by 25 enterprise clients across 20 tenants.",
        "Architected multi-tenant and sub-tenant management — API key provisioning, user administration, hierarchical structures, role-based access control, invitations, and cross-tenant asset sharing — supporting 20 tenants with multi-user configurations.",
        "Launched an in-app onboarding system using Driver.js with contextual, page-level guided tutorials, cutting feature-related support queries by 60–80%.",
        "Developed a marketing calendar with dynamic filtering, keyboard navigation, hover insights, campaign views, and scalable day-level visualization, processing ~47 scheduled posts per tenant.",
        "Designed a multi-step campaign automation workflow — from setup and channel selection through scheduling, budgeting, and publishing — consolidating previously fragmented marketing ops into a single dashboard.",
        "Implemented agentic AI systems (chat agents, workflow agents, research assistant) with dedicated UIs for creation, management, and execution, averaging 10 agent runs per tenant.",
        "Built Goodbards Drive, a document and asset manager with upload, organization, and RAG enablement — housing 300+ documents with 70–80% auto-vectorized for AI retrieval.",
        "Shipped social media analytics dashboards connecting 3–4 platforms per tenant, giving enterprise users consolidated cross-channel performance visibility.",
        "Integrated Google Analytics and Google Trends, surfacing backend data as visual dashboards used by all 25 enterprise accounts.",
        "Delivered a QR code generator (50+ codes/tenant) and a no-code embeddable chatbot builder — adopted by 7–10 tenants to deploy document-backed AI bots on external websites.",
        "Sustained a release cadence of 2 staging builds/day and 1 production deploy/week throughout active development.",
      ],
    },
    {
      id: "gb-swe",
      role: "Software Engineer",
      company: "Good Bards",
      type: "Part-time",
      start: "Sep 2024",
      end: "Oct 2024",
      stack: ["React","Next.js","TypeScript","Redux Toolkit","Material UI","Tailwind CSS","D3.js","Node.js","REST APIs"],
      bullets: [
        "Closed 48 production tickets spanning critical, medium, and minor severity in 2 months, directly stabilizing the platform pre-scale.",
        "Built a URL shortener integrated into the product ecosystem, generating 100+ shortened links per tenant.",
        "Overhauled campaign and blackout scheduling with tighter filtering logic, reducing calendar noise for marketing teams.",
        "Refactored core components with strict TypeScript typing, replacing loosely structured JS and enforcing consistent patterns across the codebase.",
      ],
    },
    {
      id: "destt",
      role: "CEO — Chief Everything Officer",
      company: "Destt",
      type: "Self-employed",
      start: "Jun 2024",
      end: "Oct 2024",
      stack: ["React Native","TypeScript","UI Kitten","Node.js","Rust","AstraDB","GCP Spanner"],
      bullets: [
        "Defined product vision, pricing model, and UX for a subscription-based ride-sharing platform that eliminated driver commissions and surge pricing.",
        "Architected a zero-commission model where drivers retain 100% of fares, validated through direct surveys with 50+ active drivers.",
        "Developed the Rider App in React Native + TypeScript over ~427 hours (~16K+ LOC), reaching ~95% feature completion across ride flow, pricing logic, and user interactions.",
        "Produced all UI/UX designs for Rider App, Driver App, and Admin Dashboard in Photoshop — 100% of screens delivered before development began.",
        "Applied to Y Combinator, incorporated reviewer feedback and early-user insights into product iteration, and engaged in YC co-founder matching discussions.",
      ],
    },
    {
      id: "exposys",
      role: "Intern",
      company: "Exposys Data Labs",
      type: "Virtual",
      start: "Nov 2021",
      end: "Dec 2021",
      stack: ["JavaScript","Node.js","MongoDB","React Native","Redux"],
      bullets: [
        "Engineered a REST API, file server, and WebSocket server in Node.js + MongoDB, serving as the sole backend for all client-side requests.",
        "Developed Meet Up, a React Native mobile app matching users by interest and enabling real-time friend requests and chat.",
      ],
    },
    {
      id: "datastax",
      role: "DataStax Hackathon Participant",
      company: "DataStax",
      type: "Finalist",
      start: "Feb 2022",
      end: "May 2022",
      stack: ["TypeScript","Cassandra","Node.js","React"],
      bullets: [
        "Selected as 1 of 4 finalists out of 2,300+ participants from 60+ countries.",
        "Developed a web-based family game and a low-code environment for managing Cassandra databases.",
      ],
    },
  ],
  projects: [
    {
      id: "zeyphr",
      name: "Zeyphr",
      stack: ["IOTA EVM","Web3","React","TypeScript","Node.js"],
      summary: "Decentralized payments & marketplace on IOTA EVM — Web2 logins, QR/tap pay, online/offline.",
      bullets: [
        "Built a decentralized payments and marketplace platform on IOTA EVM, simplifying crypto transactions through Web2-style logins, QR/tap payments, and online/offline support.",
        "Abstracted Web3 complexity with familiar authentication and payment flows, targeting consumer-scale adoption.",
      ],
      preview: "wallet",
    },
    {
      id: "subdot",
      name: "SubDot",
      stack: ["Substrate","Subsocial","React","TypeScript"],
      summary: "Decentralized social platform — user-owned data, content and governance.",
      bullets: [
        "Built a decentralized social media platform on Substrate and Subsocial giving users full control over data, content, governance, and contributor rewards.",
        "Eliminated central authority dependency, enabling community-driven decision-making and transparent content moderation.",
      ],
      preview: "social",
    },
    {
      id: "astradb",
      name: "AstraDB Navigator",
      stack: ["React","TypeScript","Node.js","Netlify Functions"],
      summary: "Multilingual no-code environment for managing Astra DB instances (EN/IT/ES/FR).",
      bullets: [
        "Built a lightweight no-code environment supporting four languages (English, Italian, Spanish, French) for managing Astra DB instances.",
      ],
      preview: "database",
    },
    {
      id: "aneta",
      name: "Aneta",
      stack: ["React","TypeScript","Cassandra","Node.js","Express.js"],
      summary: "Unified interface for organisations to manage employees and projects.",
      bullets: [
        "Built a web application enabling organisations to manage employees and projects through a unified interface.",
      ],
      preview: "org",
    },
    {
      id: "payzer",
      name: "Payzer",
      stack: ["React Native","TypeScript","PostgreSQL","Redis","Node.js"],
      summary: "Mobile app for secure national & international transactions using only a phone number.",
      bullets: [
        "Developed a mobile application enabling secure national and international transactions using only a phone number.",
      ],
      preview: "payments",
    },
  ],
  moreProjects: [
    {
      id: "zeyphr-lite",
      name: "Zeyphr Lite",
      stack: ["IOTA EVM","Web3","React","TypeScript","Node.js"],
      summary: "Stripped-down wallet companion focused on retail-style tap-to-pay flows.",
      preview: "wallet",
    },
    {
      id: "subdot-feeds",
      name: "SubDot Feeds",
      stack: ["Substrate","Subsocial","React","TypeScript"],
      summary: "Feed composition experiments on the decentralized social graph.",
      preview: "social",
    },
    {
      id: "astradb-classroom",
      name: "AstraDB Classroom",
      stack: ["React","TypeScript","Node.js","Netlify Functions"],
      summary: "No-code sandbox paired with lessons for newcomers learning Cassandra.",
      preview: "database",
    },
    {
      id: "aneta-lite",
      name: "Aneta Lite",
      stack: ["React","TypeScript","Cassandra","Node.js","Express.js"],
      summary: "A slimmer variant of Aneta aimed at small teams and single-project orgs.",
      preview: "org",
    },
    {
      id: "payzer-web",
      name: "Payzer Web",
      stack: ["React","TypeScript","PostgreSQL","Redis","Node.js"],
      summary: "Browser companion for Payzer with full desktop parity on transaction flows.",
      preview: "payments",
    },
    {
      id: "zeyphr-bridge",
      name: "Zeyphr Bridge",
      stack: ["IOTA EVM","Web3","Node.js","TypeScript"],
      summary: "Fiat/crypto bridge prototype plugged into the Zeyphr marketplace.",
      preview: "wallet",
    },
    {
      id: "subdot-mod",
      name: "SubDot Moderation",
      stack: ["Substrate","Subsocial","React","TypeScript"],
      summary: "Community moderation tools and governance primitives for SubDot spaces.",
      preview: "social",
    },
    {
      id: "astradb-viz",
      name: "AstraDB Viz",
      stack: ["React","TypeScript","Node.js","D3.js"],
      summary: "Schema and query visualizations on top of the AstraDB Navigator core.",
      preview: "database",
    },
    {
      id: "aneta-insights",
      name: "Aneta Insights",
      stack: ["React","TypeScript","Cassandra","Node.js","D3.js"],
      summary: "Reporting layer over Aneta surfacing headcount and project telemetry.",
      preview: "org",
    },
    {
      id: "payzer-remit",
      name: "Payzer Remit",
      stack: ["React Native","TypeScript","PostgreSQL","Redis","Node.js"],
      summary: "Remittance-focused branch of Payzer with optimized cross-border rails.",
      preview: "payments",
    },
  ],
  achievements: {
    hackathons: [
      { place: "1st", title: "Polkadot APAC Edition", detail: "Won Interfaces & Experiences category · presented at SJ Kunsthalle, Seoul · $18,000 + $3,000 travel grant", year: "2023" },
      { place: "2nd", title: "Polkadot Europe Edition", detail: "Interfaces & Experiences · 2,400+ global participants · presented at Pan Piper, Paris · $11,000 + $3,000 travel grant", year: "2024" },
      { place: "1st", title: "IOTA Moveathon APAC Edition", detail: "Community Best Project & 2nd Runner-Up in Payments & Consumer Applications track for Zeyphr", year: "2025" },
      { place: "★", title: "DataStax AstraDB Build-a-thon Series", detail: "Grand Winner", year: "2022" },
      { place: "2nd", title: "GlobalShala 3.0 Hackathon", detail: "1st Runner Up", year: "—" },
    ],
  },
  education: [
    { school: "Sri Venkateswara College of Engineering (SVCE)", degree: "B.Tech, Artificial Intelligence & Data Science", result: "CGPA 9.02", date: "May 2024" },
    { school: "SBOA School & Junior College (CBSE)", degree: "PCM with Computer Science", result: "Cumulative 86.2%", date: "May 2020" },
  ],
  skills: {
    Languages: ["Python","JavaScript","TypeScript","C","C++","Rust"],
    "Frameworks & Libraries": ["React","Next.js","React Native","Node.js","Express.js","Redux Toolkit","Socket.IO","Tailwind CSS","shadcn/ui","Material UI","UI Kitten","D3.js","FullCalendar","TipTap","Driver.js","Chai.js"],
    Databases: ["PostgreSQL","MongoDB","Cassandra (AstraDB)","Redis","GCP Spanner"],
    "Tools & Platforms": ["Git","Postman","Linux","Heroku","Netlify","OAuth","Adobe Photoshop","Adobe XD"],
    Technologies: ["REST APIs","WebSockets","Multi-tenant SaaS","RAG","Agentic AI","Web3 (Substrate)","IOTA EVM"],
  },
  certifications: [
    { title: "Apache Cassandra 3 Developer Associate", issuer: "DataStax Academy", year: "2022", detail: "Data modeling, CQL fluency, and operations for Apache Cassandra 3.x — earned after the AstraDB Build-a-thon." },
    { title: "Legacy Front End Developer", issuer: "freeCodeCamp", year: "2020", detail: "300+ hours across HTML, CSS, Bootstrap, jQuery, and responsive design — culminating in five projects." },
    { title: "Quality Assurance", issuer: "freeCodeCamp", year: "2021", detail: "Chai.js assertions, advanced Node.js testing patterns, and building test harnesses for REST APIs." },
    { title: "APIs & Micro-services", issuer: "freeCodeCamp", year: "2021", detail: "Node/Express APIs, routing, middleware, and deploying self-contained micro-services." },
    { title: "Scientific Computing with Python", issuer: "freeCodeCamp", year: "2021", detail: "Python fundamentals, data structures, and five applied computing projects." },
  ],
  skillProjects: {
    "React": ["gb-founding","gb-swe","datastax","subdot","astradb","aneta","zeyphr"],
    "Next.js": ["gb-founding","gb-swe"],
    "TypeScript": ["gb-founding","gb-swe","destt","datastax","zeyphr","subdot","astradb","aneta","payzer"],
    "React Native": ["destt","exposys","payzer"],
    "Node.js": ["gb-founding","gb-swe","destt","exposys","datastax","zeyphr","astradb","aneta","payzer"],
    "Rust": ["destt"],
    "Redux Toolkit": ["gb-founding","gb-swe"],
    "Tailwind CSS": ["gb-founding","gb-swe"],
    "shadcn/ui": ["gb-founding"],
    "Material UI": ["gb-swe"],
    "UI Kitten": ["destt"],
    "D3.js": ["gb-swe"],
    "Driver.js": ["gb-founding"],
    "PostgreSQL": ["payzer"],
    "MongoDB": ["exposys"],
    "Cassandra (AstraDB)": ["datastax","aneta","astradb"],
    "Redis": ["payzer"],
    "GCP Spanner": ["destt"],
    "REST APIs": ["gb-founding","gb-swe","exposys"],
    "WebSockets": ["exposys"],
    "OAuth": ["gb-founding"],
    "Web3 (Substrate)": ["subdot"],
    "IOTA EVM": ["zeyphr"],
    "RAG": ["gb-founding"],
    "Agentic AI": ["gb-founding"],
    "Multi-tenant SaaS": ["gb-founding"],
  },
};
