export const resume = {
  name: "Suraj Vijayan",
  tagline: "Founding engineer. Frontend systems at scale, shipped one brick at a time.",
  currently: "Seeking my next role — scalable software, hard problems, and a team of experienced engineers to grow alongside.",
  contact: {
    github: "its-me-sv",
    email: "surajvijay67@gmail.com",
    linkedin: "suraj-vijay-32b679224",
    instagram: "suraj_vijay_115.py",
    site: "surajvijayan.dev",
  },
  experience: [
    {
      id: "gb-founding",
      role: "Founding Software Engineer",
      company: "Good Bards",
      type: "Full-time",
      start: "Sep 2024",
      end: "May 2026",
      stack: ["React","Next.js","TypeScript","Tailwind CSS","SWR","Redux Toolkit","shadcn/ui"],
      bullets: [
        "Proposed and led a full-platform rewrite after a one-month evaluation (fixing 30+ bugs); architected a multi-tenant marketing OS bundling 15 product modules into a single Next.js application and built its entire security layer (cookie-based auth, server-side route protection, CSP, XSS sanitization); authored 82% of all commits, growing the codebase to 180,000 lines across 90+ pages.",
        "Owned code quality on the platform, onboarded and mentored the team's second engineering hire through regular PR reviews, and reviewed, tested and patched the CTO's occasional platform contributions before merge.",
        "Solo-built a white-label reseller edition for enterprise client Singapura Management — stripped the 15-module platform to a focused 4-product suite, adding a no-code RAG chatbot builder, sub-tenant management, and usage-limit guardrails; now serving 50+ downstream clients.",
        "Built an embeddable AI chatbot widget for a single client, later productized company-wide, 97% solo-authored, hardened with origin-locked JWTs, sandboxed iframes, and short-lived session tokens; adopted across 4–5 client brands.",
        "Contributed to the company's selection for Google for Startups Accelerator: AI First (Singapore), 1 of 32 startups, and presented the platform at GITEX Asia 2025.",
      ],
    },
    {
      id: "destt",
      role: "Founder",
      company: "Destt",
      type: "Self-employed",
      start: "Jun 2024",
      end: "Oct 2024",
      stack: ["React","React Native","TypeScript","Node.js","Express.js","Stripe","AstraDB (Cassandra)"],
      bullets: [
        "Founded a two-sided ride-sharing marketplace around a zero-commission incentive model, designed the pricing engine and fare logic, and built the full stack solo: rider app with driver matching, Stripe payment integration, and a Node.js/Express backend on AstraDB.",
        "Validated the model through market analysis with 50+ riders and 10+ active drivers, and applied to Y Combinator with a working demo.",
      ],
    },
    {
      id: "exposys",
      role: "Full-Stack Developer",
      company: "Exposys Data Labs",
      type: "Internship",
      start: "Nov 2021",
      end: "Dec 2021",
      stack: ["React Native","TypeScript","Node.js","Redux","MongoDB","Express.js"],
      bullets: [
        "Built and shipped Meet Up, an interest-based social app, solo in one month — a decoupled 4-service system (React Native client + three Node.js services for REST, real-time messaging and image uploads) that handled 170+ real messages across 10 active users in testing.",
      ],
    },
  ],
  projects: [
    {
      id: "zeyphr",
      name: "Zeyphr",
      stack: ["IOTA EVM","Web3","React","TypeScript","Node.js"],
      summary: "Decentralized payments & marketplace on IOTA EVM — Web2 logins, QR/tap pay, online/offline.",
      bullets: [
        "Built a decentralized payments and marketplace platform on IOTA EVM, simplifying crypto transactions through Web2-style logins, QR/tap payments, and online/offline support.",
        "Abstracted Web3 complexity with familiar authentication and payment flows, targeting consumer-scale adoption.",
      ],
      preview: "wallet",
    },
    {
      id: "subdot",
      name: "SubDot",
      stack: ["Substrate","Subsocial","React","TypeScript"],
      summary: "Decentralized social platform — user-owned data, content and governance.",
      bullets: [
        "Built a decentralized social media platform on Substrate and Subsocial giving users full control over data, content, governance, and contributor rewards.",
        "Eliminated central authority dependency, enabling community-driven decision-making and transparent content moderation.",
      ],
      preview: "social",
    },
    {
      id: "astradb",
      name: "AstraDB Navigator",
      stack: ["React","TypeScript","Node.js","Netlify Functions"],
      summary: "Multilingual no-code environment for managing Astra DB instances (EN/IT/ES/FR).",
      bullets: [
        "Built a lightweight no-code environment supporting four languages (English, Italian, Spanish, French) for managing Astra DB instances.",
      ],
      preview: "database",
    },
    {
      id: "aneta",
      name: "Aneta",
      stack: ["React","TypeScript","Cassandra","Node.js","Express.js"],
      summary: "Unified interface for organisations to manage employees and projects.",
      bullets: [
        "Built a web application enabling organisations to manage employees and projects through a unified interface — JWT auth with server-side session invalidation, real-time chat via Socket.io with deterministic room routing, and a 7-table Cassandra schema powering project-to-employee matching.",
      ],
      preview: "org",
    },
    {
      id: "payzer",
      name: "Payzer",
      stack: ["React Native","TypeScript","PostgreSQL","Redis","Node.js"],
      summary: "Mobile app for secure national & international transactions using only a phone number.",
      bullets: [
        "Developed a mobile application enabling secure national and international transactions using only a phone number — a service-separated backend with PostgreSQL triggers and functions for transactional integrity, Redis-backed token rate limiting, and an event-driven SMS pipeline via LISTEN/NOTIFY and Twilio.",
      ],
      preview: "payments",
    },
  ],
  moreProjects: [
    {
      id: "zeyphr-lite",
      name: "Zeyphr Lite",
      stack: ["IOTA EVM","Web3","React","TypeScript","Node.js"],
      summary: "Stripped-down wallet companion focused on retail-style tap-to-pay flows.",
      preview: "wallet",
    },
    {
      id: "subdot-feeds",
      name: "SubDot Feeds",
      stack: ["Substrate","Subsocial","React","TypeScript"],
      summary: "Feed composition experiments on the decentralized social graph.",
      preview: "social",
    },
    {
      id: "astradb-classroom",
      name: "AstraDB Classroom",
      stack: ["React","TypeScript","Node.js","Netlify Functions"],
      summary: "No-code sandbox paired with lessons for newcomers learning Cassandra.",
      preview: "database",
    },
    {
      id: "aneta-lite",
      name: "Aneta Lite",
      stack: ["React","TypeScript","Cassandra","Node.js","Express.js"],
      summary: "A slimmer variant of Aneta aimed at small teams and single-project orgs.",
      preview: "org",
    },
    {
      id: "payzer-web",
      name: "Payzer Web",
      stack: ["React","TypeScript","PostgreSQL","Redis","Node.js"],
      summary: "Browser companion for Payzer with full desktop parity on transaction flows.",
      preview: "payments",
    },
    {
      id: "zeyphr-bridge",
      name: "Zeyphr Bridge",
      stack: ["IOTA EVM","Web3","Node.js","TypeScript"],
      summary: "Fiat/crypto bridge prototype plugged into the Zeyphr marketplace.",
      preview: "wallet",
    },
    {
      id: "subdot-mod",
      name: "SubDot Moderation",
      stack: ["Substrate","Subsocial","React","TypeScript"],
      summary: "Community moderation tools and governance primitives for SubDot spaces.",
      preview: "social",
    },
    {
      id: "astradb-viz",
      name: "AstraDB Viz",
      stack: ["React","TypeScript","Node.js","D3.js"],
      summary: "Schema and query visualizations on top of the AstraDB Navigator core.",
      preview: "database",
    },
    {
      id: "aneta-insights",
      name: "Aneta Insights",
      stack: ["React","TypeScript","Cassandra","Node.js","D3.js"],
      summary: "Reporting layer over Aneta surfacing headcount and project telemetry.",
      preview: "org",
    },
    {
      id: "payzer-remit",
      name: "Payzer Remit",
      stack: ["React Native","TypeScript","PostgreSQL","Redis","Node.js"],
      summary: "Remittance-focused branch of Payzer with optimized cross-border rails.",
      preview: "payments",
    },
  ],
  achievements: {
    hackathons: [
      { place: "1st", title: "Polkadot APAC Edition", detail: "Won Interfaces & Experiences category · presented at SJ Kunsthalle, Seoul · $18,000 + $3,000 travel grant", year: "2023" },
      { place: "2nd", title: "Polkadot Europe Edition", detail: "Interfaces & Experiences · 2,400+ global participants · presented at Pan Piper, Paris · $11,000 + $3,000 travel grant", year: "2023" },
      { place: "1st", title: "IOTA Moveathon APAC Edition", detail: "Winner — Community Best Project, Payments & Consumer Applications track for Zeyphr · led a 4-person team · $5,000 prize", year: "2025" },
      { place: "★", title: "DataStax AstraDB Build-a-thon Series", detail: "Grand Winner — 1 of 4 finalists from 2,300+ participants across 60+ countries · $9,500 prize", year: "2022" },
      { place: "2nd", title: "GlobalShala 3.0 Hackathon", detail: "1st Runner Up", year: "—" },
      { place: "★", title: "Star Achiever Award", detail: "Principal's award, Sri Venkateswara College of Engineering, for international hackathon wins, certifications, and an 8.7 CGPA — one of just two granted this decade", year: "2024" },
      { place: "1st", title: "Kanitham 2021, National Math-Modelling Symposium", detail: "Dr. M.G.R. University's national mathematics symposium — won for a presentation on the Sieve of Eratosthenes", year: "2021" },
      { place: "📰", title: "Featured — Anna Nagar Times & Mogappair Times", detail: "Local Chennai press coverage of the Polkadot and DataStax wins", year: "—" },
    ],
  },
  education: [
    { school: "Sri Venkateswara College of Engineering (SVCE)", degree: "B.Tech, Artificial Intelligence & Data Science", result: "CGPA 8.7", date: "May 2024" },
    { school: "SBOA School & Junior College (CBSE)", degree: "PCM with Computer Science", result: "Cumulative 86.2%", date: "May 2020" },
  ],
  skills: {
    Languages: ["Python","JavaScript","TypeScript","HTML","CSS","C","C++"],
    "Frameworks & Libraries": ["React","Next.js","React Native","Node.js","Express.js","Redux Toolkit","SWR","Socket.IO","Tailwind CSS","shadcn/ui","Material UI","D3.js","FullCalendar","TipTap","Chai.js"],
    Databases: ["PostgreSQL","MongoDB","Cassandra (AstraDB)","Redis"],
    "Tools & Platforms": ["Git","Postman","Linux","Heroku","Netlify","Vercel","Docker","GitHub Actions (CI/CD)","Google Cloud Platform","OAuth","JWT","Stripe","Adobe Photoshop","Adobe XD"],
    Technologies: ["REST APIs","WebSockets","Multi-tenant SaaS","RAG","Agentic AI","Web3 (Substrate)","IOTA EVM"],
  },
  certifications: [
    { title: "Apache Cassandra 3 Developer Associate", issuer: "DataStax Academy", year: "2022", detail: "Data modeling, CQL fluency, and operations for Apache Cassandra 3.x — earned after the AstraDB Build-a-thon." },
    { title: "Redis for Startups (with JavaScript)", issuer: "Redis", year: "—", detail: "Caching patterns, data structures, and building Redis-backed features with JavaScript." },
    { title: "GitHub Actions (GH-200)", issuer: "Microsoft", year: "—", detail: "CI/CD pipeline design, workflow automation, and release management with GitHub Actions." },
    { title: "Node.js, JavaScript and REST API (Intermediate)", issuer: "HackerRank", year: "—", detail: "Intermediate-level assessment covering Node.js fundamentals, JS proficiency, and REST API design." },
    { title: "Legacy Front End Developer", issuer: "freeCodeCamp", year: "2020", detail: "300+ hours across HTML, CSS, Bootstrap, jQuery, and responsive design — culminating in five projects." },
    { title: "Quality Assurance", issuer: "freeCodeCamp", year: "2021", detail: "Chai.js assertions, advanced Node.js testing patterns, and building test harnesses for REST APIs." },
    { title: "APIs & Micro-services", issuer: "freeCodeCamp", year: "2021", detail: "Node/Express APIs, routing, middleware, and deploying self-contained micro-services." },
    { title: "Scientific Computing with Python", issuer: "freeCodeCamp", year: "2021", detail: "Python fundamentals, data structures, and five applied computing projects." },
  ],
  testimonials: [
    {
      quote: "I had the pleasure of meeting Suraj when he won an international developer competition I was running as Director of Developer Relations at DataStax. That win was no accident. Suraj is an exceptionally skilled full-stack developer with particular strength on the frontend, and his attention to detail consistently sets his work apart. What I value most about working with Suraj is his proactivity. He doesn't just execute on a brief; he comes to the table with his own ideas, and he isn't afraid to challenge mine when he sees a better path. That kind of constructive pushback is rare and incredibly valuable. Beyond the technical skill, Suraj is genuinely great to work with, kind, passionate, and driven by a real love for the craft. And critically, he ships.",
      name: "Cédrick Lunven",
      title: "CTO & Co-Founder, Good Bards · Team Leader @ IBM",
    },
    {
      quote: "I know Suraj for many years, since he was in school and participated in hackathons, to becoming the first Good Bards employee. From the early days, I have always been very impressed with his technical capabilities and his work ethic. He always shows initiative at work. Privately, he's a caring person — he constantly showed concern about my family, which I appreciate. Suraj is a great hire and a tough act to match.",
      name: "Alan Ho",
      title: "CEO & Co-Founder, Good Bards · Adjunct Faculty @ SMU",
    },
  ],
  volunteering: [
    {
      org: "Peace with Smiles",
      role: "Volunteer · Board Member since May 2026",
      period: "Feb 2026 — Present",
      detail: "Community nonprofit running quarterly events",
      bullets: [
        "Appointed to the board within three months of joining, in recognition of performance and consistent involvement.",
        "Ran Kids-2-Kids, a clothing drive collecting gently used clothes from daycare and preschool families for orphaned children.",
      ],
    },
  ],
  interests: [
    { label: "ESP32 IoT builds", detail: "Phone-controlled fans and lights in college, and a long-distance \"touch watch\" for my cousins — swipe to a photo, pick an emotion, their watch shows it with a chime." },
    { label: "Outdoors & fitness", detail: "Trekking and adrenaline sports; swimming and the gym." },
    { label: "Off the keyboard", detail: "Studying history and cultures; singing." },
    { label: "Currently learning", detail: "GoLang, AWS, Greek recipes." },
  ],
  skillProjects: {
    "React": ["gb-founding","subdot","astradb","aneta","zeyphr"],
    "Next.js": ["gb-founding"],
    "TypeScript": ["gb-founding","destt","exposys","zeyphr","subdot","astradb","aneta","payzer"],
    "React Native": ["destt","exposys","payzer"],
    "Node.js": ["destt","exposys","zeyphr","astradb","aneta","payzer"],
    "Redux Toolkit": ["gb-founding"],
    "SWR": ["gb-founding"],
    "Tailwind CSS": ["gb-founding"],
    "shadcn/ui": ["gb-founding"],
    "Material UI": [],
    "D3.js": [],
    "PostgreSQL": ["payzer"],
    "MongoDB": ["exposys"],
    "Cassandra (AstraDB)": ["destt","aneta","astradb"],
    "Redis": ["payzer"],
    "REST APIs": ["gb-founding","exposys"],
    "WebSockets": ["exposys"],
    "OAuth": ["gb-founding"],
    "Stripe": ["destt"],
    "Web3 (Substrate)": ["subdot"],
    "IOTA EVM": ["zeyphr"],
    "RAG": ["gb-founding"],
    "Agentic AI": ["gb-founding"],
    "Multi-tenant SaaS": ["gb-founding"],
  },
};
